# Generated by Django 5.2.5 on 2025-08-22 23:37

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="certifications/"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=80)),
                ("project_type", models.CharField(blank=True, max_length=140)),
                ("message", models.TextField(blank=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="leads/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=240)),
                ("slug", models.SlugField(blank=True, max_length=260, unique=True)),
                ("excerpt", models.CharField(blank=True, max_length=300)),
                ("body", ckeditor.fields.RichTextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="blog/")),
                ("published", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("industrial", "Industrial"),
                            ("commercial", "Commercial"),
                            ("public", "Public Works"),
                            ("residential", "Residential"),
                        ],
                        max_length=32,
                    ),
                ),
                ("state", models.CharField(max_length=80)),
                ("year", models.PositiveIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("main", "Main Contractor"),
                            ("sub", "Sub-contractor"),
                        ],
                        max_length=16,
                    ),
                ),
                ("materials", models.CharField(blank=True, max_length=200)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="projects/covers/"
                    ),
                ),
                ("description", ckeditor.fields.RichTextField(blank=True)),
                ("results", models.TextField(blank=True)),
                ("testimonial", models.CharField(blank=True, max_length=280)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=140, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                ("summary", models.CharField(blank=True, max_length=240)),
                ("body", ckeditor.fields.RichTextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=60)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140)),
                ("role", models.CharField(max_length=140)),
                ("bio", models.TextField(blank=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="team/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="projects/gallery/")),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="project",
            name="services",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="core.service"
            ),
        ),
    ]
